name: Check for runtime version changes [temp]

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  Check-For-Changes-To-Runtime-File:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if runtime.ts has been modified
        id: detect_runtime_change
        run: |
          files=$(git diff-tree --no-commit-id --name-only -r HEAD^1 HEAD)
          runtime_changed='false'
          for changed_file in $files; do
            if [ "$changed_file" = "packages/teams-js/src/public/runtime.ts" ]; then
              runtime_changed='true'
            fi
          done
          echo "runtime_changed=$runtime_changed" >> $GITHUB_OUTPUT
      - name: 'Comment on PR'
        if: steps.detect_runtime_change.outputs.runtime_changed == 'true'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'This pull request contains changes to the runtime.ts file. If you, as the author of this PR, have made changes to the Runtime interface please review RUNTIME.md to determine if a new runtime version is required. Please reply to this comment stating what changes, if any, were made to the runtime object and whether a new runtime version was required.'
            });
